# Generated by Django 3.1.3 on 2021-02-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('dividend_date', models.DateField()),
                ('dividend_value', models.FloatField()),
                ('payment_date', models.DateField()),
                ('type', models.CharField(max_length=150)),
                ('type_short', models.CharField(max_length=10)),
                ('yeild', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'dividends',
            },
        ),
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price_avg', models.FloatField(verbose_name='Цена за единицу')),
                ('base_cost', models.FloatField(verbose_name='Базовая стоимость')),
                ('current_price', models.FloatField(verbose_name='Текущая цена')),
                ('cost', models.FloatField(verbose_name='Стоимость')),
                ('profit', models.FloatField(verbose_name='Прибыль')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCostChange',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('stock_cost', models.FloatField(verbose_name='Стоимость')),
                ('rub_cost', models.FloatField(verbose_name='Рубль')),
                ('usd_cost', models.FloatField(verbose_name='Доллар')),
                ('deposit', models.FloatField(verbose_name='Депозит')),
                ('commission', models.FloatField(verbose_name='Комиссия')),
                ('dividend', models.FloatField(verbose_name='Дивиденды')),
                ('stock_contain', models.JSONField(blank=True, default=None, verbose_name='Состав')),
            ],
        ),
        migrations.CreateModel(
            name='StockTimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=10)),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Open', models.FloatField()),
                ('Close', models.FloatField()),
                ('Volume', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('operation', models.CharField(choices=[('buy', 'Покупка акций'), ('sell', 'Продажа акций'), ('currency_conversion', 'Конвертация валют'), ('commission', 'Комиссия'), ('deposit', 'Электронный перевод средств')], default='deposit', max_length=200)),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('commission', models.FloatField()),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default=2, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='DividendPayments',
            fields=[
                ('dividend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.dividends')),
                ('amount', models.IntegerField(blank=True, verbose_name='Количество')),
            ],
        ),
    ]
