# Generated by Django 3.1.3 on 2021-02-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dividends',
            table=None,
        ),
    ]
